//! Checkerboard absolute-pattern generation — a 50/50 black-and-white carrier
//! carrying the same LFSR position code as [`megarena`](crate::megarena).
//!
//! # Why a checkerboard
//!
//! A megarena is sparse: isolated dots on a dark field, ~25% fill. Most of the
//! sensor's dynamic range carries no signal, and the code is written by
//! *removing* dots, so the local mean brightness drifts with the code. A
//! checkerboard is 50/50 by construction and spends all of its contrast on the
//! carrier.
//!
//! # The carrier lives on the diagonals
//!
//! Writing `s(x) = sign(cos(π(x/a − ½)))` for the square wave of square side
//! `a`, the checkerboard is `s(x)·s(y)`, whose lowest Fourier terms are
//!
//! ```text
//! (8/π²)·[ cos(π((x+y)/a − 1)) + cos(π(x−y)/a) ]
//! ```
//!
//! — two carriers at ±45° to the square edges, each of amplitude `8/π² ≈ 0.81`
//! on a ±1 signal (`0.405` on a `[0,1]` image), against `0.25` for the
//! megarena's raised-cosine dot. Nothing sits on the axes: the square-wave
//! product keeps only odd×odd harmonics. So the two-peak spectral search works
//! unchanged, and [`phase1_at`](Checkerboard::phase1_at) /
//! [`phase2_at`](Checkerboard::phase2_at) are the diagonal phases above. Both
//! read `+1` at the centre of a white square and `−1` at a black one, so the
//! phase pair indexes the squares directly:
//!
//! ```text
//! i + j = φ₁/π      i − j = φ₂/π       (at square centres)
//! ```
//!
//! # How the code is written
//!
//! Squares are grouped into 3×3 supercells. Two squares per supercell are
//! *coding sites*: `(1,0)` carries the x-code bit of its supercell column,
//! `(0,1)` the y-code bit of its supercell row. A coding site whose bit is `0`
//! is **inverted** — painted the colour opposite to its checkerboard parity.
//! Every other square is untouched. Reading a bit is then just
//!
//! > does this square's colour disagree with the parity `(i+j) mod 2`?
//!
//! Three properties make this work, and they are the whole design:
//!
//! - **Phase-neutral.** A square centre is an extremum of both carriers, and
//!   inverting a square flips its contribution from `+1` to `−1`. In the carrier
//!   basis the perturbation is therefore purely *real*: it shrinks the peak, it
//!   never rotates it. This is the megarena's own trick (code on the *middle*
//!   period of each triple) transposed, and it is why the absolute code cannot
//!   corrupt the fine pose.
//! - **Balanced.** Coding sites sit at `(3k+1, 3l)` and `(3k, 3l+1)`, whose
//!   parity is `(k+l+1) mod 2` — it alternates. Half the inversions are
//!   white→black and half black→white, so the 50/50 fill holds whatever the
//!   code says, with no code-dependent brightness drift.
//! - **Cheap.** 2 of 9 squares are coding sites, ~half of them inverted, so
//!   ~1/9 of squares are flipped and the carrier keeps `1 − 2/9 ≈ 0.78` of its
//!   amplitude. The removed energy goes into a flat pedestal, not a coherent
//!   line, because an LFSR sequence is spectrally white.
//!
//! # Reading it back
//!
//! Every window of `order` bits is unique, so `order` bits along each axis fix
//! the absolute position. But an LFSR sequence contains *every* non-zero
//! `order`-bit word, so a single window can never be rejected: a wrong
//! orientation or a wrong colour-parity hypothesis still "decodes", to the wrong
//! place. The decoder therefore over-reads — `order + r` bits — locates on the
//! first `order` and requires the remaining `r` to agree, which rejects a wrong
//! hypothesis with probability `1 − 2⁻ʳ`. See [`vernier_pose::checkerboard`].
//!
//! # The code period is odd, and that matters
//!
//! [`range_squares`](Checkerboard::range_squares) is `3·(2ⁿ − 1)` — 765 squares
//! at order 8, 12 285 at order 12 — and it is always **odd**. The checkerboard
//! parity has period 2, so shifting by one whole code period lands on the same
//! code with the colours swapped: the pattern only truly repeats after *two*
//! code periods.
//!
//! The decoder reports position modulo one code period, which is the
//! conservative reading and what [`range_squares`] promises. The spare factor of
//! two is real — the period lattice is generated by `(2P, 0)`, `(0, 2P)` and
//! `(P, P)` for `P = 3·(2ⁿ − 1)`, which is twice the area of a `P × P` cell — but
//! claiming it means resolving a parity that constrains only `Δi + Δj`, jointly
//! across the two axes. Left on the table deliberately.

use vernier_core::scalar::consts::{PI, SQRT_2};
use vernier_core::{GrayImage, Real};

use crate::PatternPose;
use crate::lfsr::Lfsr;
use crate::render::{into_pattern_frame, render_with};

/// Squares per supercell edge. Three, as in the megarena: it is the smallest
/// group that leaves a coding site surrounded by untouched squares to calibrate
/// black and white against.
pub const CELL: i64 = 3;

/// Position of the x-code site within a supercell, as `(i mod 3, j mod 3)`.
pub const X_SITE: (i64, i64) = (1, 0);

/// Position of the y-code site within a supercell.
pub const Y_SITE: (i64, i64) = (0, 1);

/// Position of the `u`-code site under [`CodeLayout::Diagonals`], as
/// `(u mod 3, v mod 3)` — the direct mirror of [`X_SITE`] in the rotated frame.
pub const U_SITE: (i64, i64) = (1, 0);

/// Position of the `v`-code site under [`CodeLayout::Diagonals`].
pub const V_SITE: (i64, i64) = (0, 1);

/// Which axis's code bit a coding square carries.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CodeAxis {
    /// Square encodes the x-direction code bit of its supercell column.
    X,
    /// Square encodes the y-direction code bit of its supercell row.
    Y,
}

/// Which directions the position code is written along.
///
/// The squares and the carriers are rigidly locked 45° apart — the carriers are
/// the `cos(π(x±y)/a)` terms, always at ±45° to the square edges — so tilting
/// the pattern tilts both together. What *is* free is the direction the code
/// runs, and that is what this selects.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum CodeLayout {
    /// Indexed by the square-lattice axes `(i, j)`: the original design. The
    /// code grid runs parallel to the square edges, 45° away from the carriers,
    /// and the decoder recovers `(i, j)` from the phase pair as
    /// `((φ₁±φ₂)/2π)`.
    #[default]
    LatticeAxes,
    /// Indexed by the lattice diagonals `(i+j, i−j)`: the code runs *parallel*
    /// to the carriers, so each phase plane indexes one code axis directly with
    /// no combination step — `φ₁/π` is the first code coordinate, `φ₂/π` the
    /// second.
    ///
    /// Rendered at 45° this is the "diamond squares, upright code grid" layout:
    /// the tiles read as diamonds while the supercell structure lines up with
    /// the image axes.
    ///
    /// The three design properties survive the change. Coding sites are still
    /// exactly 2/9 of squares, because `(i, j) ↦ (i+j, i−j)` is a bijection
    /// modulo 3 (2 is invertible there), so the residue pair is still uniform
    /// over the nine cells. Inversions are still balanced, because a site's
    /// parity is `u mod 2` and each family's `u` advances by 3 per supercell,
    /// alternating colour. And inverting a square centre is still phase-neutral,
    /// which never depended on *which* squares were chosen.
    ///
    /// The one real cost is range: lines of constant `i+j` are `a/√2` apart
    /// rather than `a`, so the same bit count spans `√2` less distance. See
    /// [`Checkerboard::range_px`].
    Diagonals,
}

/// Parameters of a coded checkerboard pattern.
#[derive(Clone, Debug)]
pub struct Checkerboard {
    /// Side of one checkerboard square, in pixels.
    pub square_px: Real,
    /// LFSR order = bits per unique window. Determines the absolute range.
    pub order: u32,
    /// The absolute code sequence, shared by both axes (orientation is resolved
    /// by over-reading, not by using distinct polynomials).
    code: Lfsr,
    /// LFSR index of the bit at supercell 0, mirroring
    /// [`Megarena::with_lfsr_offset`](crate::megarena::Megarena::with_lfsr_offset):
    /// keeps the decode window off the sequence boundary.
    lfsr_offset: i64,
    /// Sub-samples per pixel edge when rendering. The pattern is binary with
    /// hard edges, so point sampling would alias badly and move the measured
    /// carrier phase; 4×4 box sampling is enough to render a clean edge.
    supersample: u32,
    /// Which directions the code runs along.
    layout: CodeLayout,
}

impl Checkerboard {
    /// Builds a coded checkerboard, or `None` if `order` is unsupported (see
    /// [`Lfsr::maximal`]).
    pub fn new(square_px: Real, order: u32) -> Option<Self> {
        let code = Lfsr::maximal(order)?;
        Some(Self {
            square_px,
            order,
            code,
            lfsr_offset: 0,
            supersample: 4,
            layout: CodeLayout::LatticeAxes,
        })
    }

    /// Sets which directions the position code runs along.
    pub fn with_code_layout(mut self, layout: CodeLayout) -> Self {
        self.layout = layout;
        self
    }

    /// Which directions the code runs along.
    pub fn code_layout(&self) -> CodeLayout {
        self.layout
    }

    /// Sets the LFSR index placed at supercell 0.
    pub fn with_lfsr_offset(mut self, offset: i64) -> Self {
        self.lfsr_offset = offset;
        self
    }

    /// Sets the render supersampling factor (sub-samples per pixel edge).
    pub fn with_supersample(mut self, supersample: u32) -> Self {
        self.supersample = supersample.max(1);
        self
    }

    /// The absolute code sequence, for the decoder to match windows against.
    pub fn code(&self) -> &Lfsr {
        &self.code
    }

    /// Distance between successive carrier fringes, `a·√2` — what a detector
    /// should be told the "period" is, *not* the square side. The carriers run
    /// along the diagonals, so one carrier period spans two squares edge-to-edge
    /// and `a√2` along the diagonal itself.
    pub fn carrier_period_px(&self) -> Real {
        self.square_px * SQRT_2
    }

    /// Absolute range along one code axis, in code steps: `CELL · (2^order − 1)`.
    ///
    /// A "step" is one square under [`CodeLayout::LatticeAxes`] and one diagonal
    /// index under [`CodeLayout::Diagonals`]; those are not the same distance,
    /// so use [`range_px`](Self::range_px) to compare the two layouts.
    pub fn range_squares(&self) -> i64 {
        CELL * self.code.len() as i64
    }

    /// Absolute range along one code axis in pixels.
    ///
    /// Lines of constant `i` are `a` apart, but lines of constant `i+j` are only
    /// `a/√2` apart, so indexing the code diagonally buys the shorter range by
    /// exactly `√2` for the same square side and bit count.
    pub fn range_px(&self) -> Real {
        let steps = self.range_squares() as Real;
        match self.layout {
            CodeLayout::LatticeAxes => steps * self.square_px,
            CodeLayout::Diagonals => steps * self.square_px / SQRT_2,
        }
    }

    /// The code bit of supercell `index` along either axis.
    pub fn code_bit(&self, index: i64) -> u8 {
        let k = (index + self.lfsr_offset).rem_euclid(self.code.len() as i64) as usize;
        self.code.bit_at(k)
    }

    /// Which code bit, if any, the square at `(i, j)` carries.
    pub fn coding_axis(i: i64, j: i64) -> Option<CodeAxis> {
        let within = (i.rem_euclid(CELL), j.rem_euclid(CELL));
        if within == X_SITE {
            Some(CodeAxis::X)
        } else if within == Y_SITE {
            Some(CodeAxis::Y)
        } else {
            None
        }
    }

    /// Diagonal coordinates of square `(i, j)`: `(i+j, i−j)`, the pair the two
    /// carrier phases read off directly (`φ₁ = πu`, `φ₂ = πv` at centres).
    ///
    /// Only pairs with `u ≡ v (mod 2)` name a real square — the map is a
    /// rotation by 45° and a scaling by `√2`, so its image is the even
    /// sublattice of `Z²`.
    pub fn diagonal_coords(i: i64, j: i64) -> (i64, i64) {
        (i + j, i - j)
    }

    /// Which code bit, if any, the square at diagonal coordinates `(u, v)`
    /// carries under [`CodeLayout::Diagonals`]. Same residue test as
    /// [`coding_axis`](Self::coding_axis), applied in the rotated frame.
    /// Which code bit, if any, the square at diagonal coordinates `(u, v)`
    /// carries under [`CodeLayout::Diagonals`].
    pub fn diagonal_coding_axis(u: i64, v: i64) -> Option<CodeAxis> {
        let within = (u.rem_euclid(CELL), v.rem_euclid(CELL));
        if within == U_SITE {
            Some(CodeAxis::X)
        } else if within == V_SITE {
            Some(CodeAxis::Y)
        } else {
            None
        }
    }

    /// Whether the square at `(i, j)` is painted against its checkerboard
    /// parity. True only at a coding site whose bit is `0`.
    pub fn square_inverted(&self, i: i64, j: i64) -> bool {
        match self.layout {
            CodeLayout::LatticeAxes => match Self::coding_axis(i, j) {
                Some(CodeAxis::X) => self.code_bit(i.div_euclid(CELL)) == 0,
                Some(CodeAxis::Y) => self.code_bit(j.div_euclid(CELL)) == 0,
                None => false,
            },
            CodeLayout::Diagonals => {
                let (u, v) = Self::diagonal_coords(i, j);
                match Self::diagonal_coding_axis(u, v) {
                    Some(CodeAxis::X) => self.code_bit(u.div_euclid(CELL)) == 0,
                    Some(CodeAxis::Y) => self.code_bit(v.div_euclid(CELL)) == 0,
                    None => false,
                }
            }
        }
    }

    /// The parity colour of square `(i, j)` ignoring the code: white when
    /// `i + j` is even.
    pub fn parity_is_white(i: i64, j: i64) -> bool {
        (i + j).rem_euclid(2) == 0
    }

    /// The colour actually painted at square `(i, j)`.
    pub fn square_is_white(&self, i: i64, j: i64) -> bool {
        Self::parity_is_white(i, j) != self.square_inverted(i, j)
    }

    /// Square indices containing the pattern-frame point `(x, y)`.
    pub fn square_at(&self, x: Real, y: Real) -> (i64, i64) {
        (
            (x / self.square_px).floor() as i64,
            (y / self.square_px).floor() as i64,
        )
    }

    /// Ideal intensity at pattern-frame `(x, y)`: `1.0` white, `0.0` black.
    /// Binary with hard edges — [`render`](Self::render) box-filters it.
    pub fn intensity_at(&self, x: Real, y: Real) -> Real {
        let (i, j) = self.square_at(x, y);
        if self.square_is_white(i, j) { 1.0 } else { 0.0 }
    }

    /// Ideal intensity of the *uncoded* checkerboard — the same carrier with
    /// every coding site left at its parity colour. For measuring what the code
    /// costs.
    pub fn plain_intensity_at(&self, x: Real, y: Real) -> Real {
        let (i, j) = self.square_at(x, y);
        if Self::parity_is_white(i, j) {
            1.0
        } else {
            0.0
        }
    }

    /// First diagonal carrier phase (radians): `π((x+y)/a − 1)`. Equals `π(i+j)`
    /// at the centre of square `(i, j)`, so `cos φ₁ = +1` on white squares.
    pub fn phase1_at(&self, x: Real, y: Real) -> Real {
        PI * ((x + y) / self.square_px - 1.0)
    }

    /// Second diagonal carrier phase (radians): `π(x−y)/a`. Equals `π(i−j)` at
    /// the centre of square `(i, j)`.
    pub fn phase2_at(&self, x: Real, y: Real) -> Real {
        PI * (x - y) / self.square_px
    }

    /// Inverts [`phase1_at`]/[`phase2_at`]: the square indices a pair of
    /// unwrapped carrier phases points at. This is how the decoder turns fitted
    /// phase planes into a square grid it can sample.
    pub fn square_from_phases(phase1: Real, phase2: Real) -> (i64, i64) {
        let sum = phase1 / PI; // i + j
        let difference = phase2 / PI; // i − j
        (
            ((sum + difference) * 0.5).round() as i64,
            ((sum - difference) * 0.5).round() as i64,
        )
    }

    /// Renders the pattern at `pose` into a `width × height` image, box-filtered
    /// over `supersample²` sub-samples per pixel.
    pub fn render(&self, width: usize, height: usize, pose: &PatternPose) -> GrayImage {
        self.render_field(width, height, pose, false)
    }

    /// Renders the *uncoded* checkerboard at the same pose — the reference the
    /// coded pattern is compared against.
    pub fn render_plain(&self, width: usize, height: usize, pose: &PatternPose) -> GrayImage {
        self.render_field(width, height, pose, true)
    }

    fn render_field(
        &self,
        width: usize,
        height: usize,
        pose: &PatternPose,
        plain: bool,
    ) -> GrayImage {
        let center_x = width as Real / 2.0;
        let center_y = height as Real / 2.0;
        let n = self.supersample as Real;
        let step = 1.0 / n;
        let first = 0.5 * step - 0.5; // sub-sample offsets centred on the pixel

        render_with(width, height, |px, py| {
            let mut sum = 0.0;
            for sub_y in 0..self.supersample {
                for sub_x in 0..self.supersample {
                    let sx = px + first + sub_x as Real * step;
                    let sy = py + first + sub_y as Real * step;
                    let (xp, yp) = into_pattern_frame(sx, sy, center_x, center_y, pose.theta);
                    let (x, y) = (xp - pose.x, yp - pose.y);
                    sum += if plain {
                        self.plain_intensity_at(x, y)
                    } else {
                        self.intensity_at(x, y)
                    };
                }
            }
            sum / (n * n)
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Complex carrier amplitude of a square-indexed field, evaluated exactly on
    /// the lattice: `Σ c(i,j)·e^{−iφ}` with `φ₁ = π(i+j)`, `φ₂ = π(i−j)`.
    /// Returns `(real, imaginary)` normalized by the square count.
    fn lattice_carrier(pattern: &Checkerboard, n: i64, axis1: bool, coded: bool) -> (Real, Real) {
        let (mut re, mut im) = (0.0, 0.0);
        for i in 0..n {
            for j in 0..n {
                let white = if coded {
                    pattern.square_is_white(i, j)
                } else {
                    Checkerboard::parity_is_white(i, j)
                };
                let c = if white { 1.0 } else { -1.0 };
                let phase = if axis1 {
                    PI * (i + j) as Real
                } else {
                    PI * (i - j) as Real
                };
                re += c * phase.cos();
                im += -c * phase.sin();
            }
        }
        let count = (n * n) as Real;
        (re / count, im / count)
    }

    #[test]
    fn builds_for_valid_order() {
        let c = Checkerboard::new(8.0, 8).unwrap();
        assert_eq!(c.order, 8);
        assert_eq!(c.code().len(), 255);
        assert_eq!(c.range_squares(), 765);
    }

    #[test]
    fn rejects_unsupported_order() {
        assert!(Checkerboard::new(8.0, 3).is_none());
    }

    #[test]
    fn only_coding_sites_are_ever_inverted() {
        let c = Checkerboard::new(8.0, 6).unwrap();
        for i in -30..30i64 {
            for j in -30..30i64 {
                if Checkerboard::coding_axis(i, j).is_none() {
                    assert!(!c.square_inverted(i, j), "({i},{j}) inverted off-site");
                }
            }
        }
    }

    #[test]
    fn coding_sites_follow_their_axis_bit() {
        let c = Checkerboard::new(8.0, 6).unwrap();
        for k in 0..20i64 {
            for l in 0..20i64 {
                let (xi, xj) = (CELL * k + X_SITE.0, CELL * l + X_SITE.1);
                assert_eq!(
                    c.square_inverted(xi, xj),
                    c.code_bit(k) == 0,
                    "x site of cell ({k},{l})"
                );
                let (yi, yj) = (CELL * k + Y_SITE.0, CELL * l + Y_SITE.1);
                assert_eq!(
                    c.square_inverted(yi, yj),
                    c.code_bit(l) == 0,
                    "y site of cell ({k},{l})"
                );
            }
        }
    }

    #[test]
    fn coding_sites_alternate_colour_so_fill_stays_balanced() {
        // The balance claim: inverting coding sites must not tilt the 50/50
        // black/white split, because the sites themselves alternate parity.
        let c = Checkerboard::new(8.0, 8).unwrap();
        let n = 3 * 255; // one full code period of supercells
        let mut white = 0i64;
        for i in 0..n {
            for j in 0..n {
                if c.square_is_white(i, j) {
                    white += 1;
                }
            }
        }
        let fill = white as Real / (n * n) as Real;
        assert!((fill - 0.5).abs() < 1e-3, "fill {fill} drifted from 50/50");
    }

    /// The three design properties, asserted for whichever layout is given.
    fn assert_design_properties(c: &Checkerboard, label: &str) {
        let n = 3 * 255;

        // Cheap: coding sites stay 2 of every 9 squares.
        let mut sites = 0i64;
        for i in 0..n {
            for j in 0..n {
                let coding = match c.code_layout() {
                    CodeLayout::LatticeAxes => Checkerboard::coding_axis(i, j).is_some(),
                    CodeLayout::Diagonals => {
                        let (u, v) = Checkerboard::diagonal_coords(i, j);
                        Checkerboard::diagonal_coding_axis(u, v).is_some()
                    }
                };
                if coding {
                    sites += 1;
                }
            }
        }
        let density = sites as Real / (n * n) as Real;
        assert!(
            (density - 2.0 / 9.0).abs() < 1e-3,
            "{label}: coding-site density {density} should be 2/9"
        );

        // Balanced: the inversions must not tilt the 50/50 fill.
        let mut white = 0i64;
        for i in 0..n {
            for j in 0..n {
                if c.square_is_white(i, j) {
                    white += 1;
                }
            }
        }
        // Global fill only. For the diagonal layout this holds because the two
        // families' colour biases cancel, not because either is balanced —
        // see `diagonal_code_bands_are_monochrome_by_construction`.
        let fill = white as Real / (n * n) as Real;
        assert!((fill - 0.5).abs() < 2e-3, "{label}: fill {fill} drifted from 50/50");

        // Phase-neutral: the code perturbation stays purely real in the carrier
        // basis, so it shrinks the peak without rotating it.
        for axis1 in [true, false] {
            let (_, coded_im) = lattice_carrier(c, n, axis1, true);
            assert!(
                coded_im.abs() < 1e-9,
                "{label}: code rotated carrier {}, imaginary part {coded_im}",
                if axis1 { 1 } else { 2 }
            );
        }
    }

    #[test]
    fn diagonal_layout_keeps_every_design_property() {
        let diagonal = Checkerboard::new(8.0, 8)
            .unwrap()
            .with_code_layout(CodeLayout::Diagonals);
        assert_design_properties(&diagonal, "diagonals");

        // And the original is unchanged by the refactor.
        let axes = Checkerboard::new(8.0, 8).unwrap();
        assert_eq!(axes.code_layout(), CodeLayout::LatticeAxes);
        assert_design_properties(&axes, "lattice axes");
    }

    #[test]
    fn diagonal_layout_actually_moves_the_code() {
        // Same parameters, different layout: the painted colours must differ,
        // or the option would be a no-op.
        let axes = Checkerboard::new(8.0, 8).unwrap();
        let diagonal = axes.clone().with_code_layout(CodeLayout::Diagonals);

        let mut differing = 0;
        for i in 0..90 {
            for j in 0..90 {
                if axes.square_is_white(i, j) != diagonal.square_is_white(i, j) {
                    differing += 1;
                }
            }
        }
        assert!(differing > 0, "the two layouts paint identical squares");
    }

    /// Colour balance *within each code band*, which is the property that
    /// actually protects the measurement.
    ///
    /// A global 50/50 fill can hide a broken design: two families whose colour
    /// biases happen to cancel still average out overall while each one drags
    /// the local brightness with the code. What matters is that the sites
    /// sharing a single code bit — the ones that flip together — are half white
    /// and half black, so flipping them is brightness-neutral where it happens.
    fn worst_band_imbalance(c: &Checkerboard) -> Real {
        let n = 240;
        // For each code band, count the colours of the sites it owns.
        let mut bands: std::collections::HashMap<(bool, i64), (i64, i64)> =
            std::collections::HashMap::new();
        for i in -n..n {
            for j in -n..n {
                let (u, v) = Checkerboard::diagonal_coords(i, j);
                let (axis, band) = match c.code_layout() {
                    CodeLayout::LatticeAxes => match Checkerboard::coding_axis(i, j) {
                        Some(CodeAxis::X) => (true, i.div_euclid(CELL)),
                        Some(CodeAxis::Y) => (false, j.div_euclid(CELL)),
                        None => continue,
                    },
                    CodeLayout::Diagonals => match Checkerboard::diagonal_coding_axis(u, v) {
                        Some(CodeAxis::X) => (true, u.div_euclid(CELL)),
                        Some(CodeAxis::Y) => (false, v.div_euclid(CELL)),
                        None => continue,
                    },
                };
                let entry = bands.entry((axis, band)).or_insert((0, 0));
                if Checkerboard::parity_is_white(i, j) {
                    entry.0 += 1;
                } else {
                    entry.1 += 1;
                }
            }
        }
        // Ignore bands clipped by the edge of the scanned window.
        bands
            .values()
            .filter(|(w, b)| w + b >= 40)
            .map(|&(w, b)| ((w - b).abs() as Real) / ((w + b) as Real))
            .fold(0.0, Real::max)
    }

    #[test]
    fn lattice_axis_code_bands_are_colour_balanced() {
        let c = Checkerboard::new(8.0, 8).unwrap();
        let worst = worst_band_imbalance(&c);
        assert!(
            worst < 0.2,
            "a code band is {:.0}% colour-biased, so flipping it shifts the local \
             brightness",
            worst * 100.0
        );
    }

    #[test]
    fn diagonal_code_bands_are_monochrome_by_construction() {
        // The structural cost of running the code along the carriers, recorded
        // so nobody adopts the layout without meeting it.
        //
        // A square's colour is `(i+j) mod 2 = u mod 2`, so colour is *constant*
        // along a line of constant u — the diagonals of a checkerboard are
        // monochrome. This layout writes its u code along exactly those lines,
        // so every coding site of a band is the same colour and flipping the
        // band moves the local brightness. The lattice-axis layout runs its
        // bands along lines where colour alternates, which is why it gets the
        // balance for free.
        //
        // It cannot be tuned away by moving the sites: u and v always share a
        // parity (a square exists only where u ≡ v mod 2), so pinning a
        // family's residues pins its colour too.
        let c = Checkerboard::new(8.0, 8)
            .unwrap()
            .with_code_layout(CodeLayout::Diagonals);
        let worst = worst_band_imbalance(&c);
        assert!(
            worst > 0.99,
            "expected fully monochrome code bands, got {:.0}% bias",
            worst * 100.0
        );
    }

    #[test]
    fn diagonal_layout_costs_sqrt2_of_range() {
        let axes = Checkerboard::new(8.0, 8).unwrap();
        let diagonal = axes.clone().with_code_layout(CodeLayout::Diagonals);

        // Same bit count either way...
        assert_eq!(axes.range_squares(), diagonal.range_squares());
        // ...but constant-(i+j) lines are a/sqrt(2) apart, not a.
        let ratio = axes.range_px() / diagonal.range_px();
        assert!((ratio - SQRT_2).abs() < 1e-9, "range ratio {ratio} should be sqrt(2)");
    }

    #[test]
    fn code_is_phase_neutral_on_the_lattice() {
        // The load-bearing property: in the carrier basis the code perturbation
        // is purely real, so it shrinks the peak without rotating it. Any
        // imaginary part would be a phase bias, i.e. a fine-pose error.
        let c = Checkerboard::new(8.0, 8).unwrap();
        let n = 3 * 255;
        for axis1 in [true, false] {
            let (plain_re, plain_im) = lattice_carrier(&c, n, axis1, false);
            let (coded_re, coded_im) = lattice_carrier(&c, n, axis1, true);
            assert!((plain_re - 1.0).abs() < 1e-9, "plain carrier {plain_re}");
            assert!(plain_im.abs() < 1e-9, "plain carrier not real");
            assert!(
                coded_im.abs() < 1e-9,
                "coded carrier has imaginary part {coded_im} — phase bias"
            );
            // ~1/9 of squares inverted, each flipping +1 → −1.
            assert!(
                (coded_re - 0.78).abs() < 0.02,
                "coded carrier amplitude {coded_re}, expected ≈0.78"
            );
        }
    }

    #[test]
    fn phases_index_the_squares() {
        let c = Checkerboard::new(7.0, 6).unwrap();
        for i in -10..10i64 {
            for j in -10..10i64 {
                let x = (i as Real + 0.5) * c.square_px;
                let y = (j as Real + 0.5) * c.square_px;
                let recovered =
                    Checkerboard::square_from_phases(c.phase1_at(x, y), c.phase2_at(x, y));
                assert_eq!(recovered, (i, j), "square ({i},{j})");
            }
        }
    }

    #[test]
    fn carriers_peak_on_white_squares() {
        let c = Checkerboard::new(7.0, 6).unwrap();
        for i in -6..6i64 {
            for j in -6..6i64 {
                let x = (i as Real + 0.5) * c.square_px;
                let y = (j as Real + 0.5) * c.square_px;
                let expected = if Checkerboard::parity_is_white(i, j) {
                    1.0
                } else {
                    -1.0
                };
                assert!((c.phase1_at(x, y).cos() - expected).abs() < 1e-9);
                assert!((c.phase2_at(x, y).cos() - expected).abs() < 1e-9);
            }
        }
    }

    #[test]
    fn carrier_period_is_the_square_diagonal() {
        let c = Checkerboard::new(10.0, 6).unwrap();
        assert!((c.carrier_period_px() - 10.0 * SQRT_2).abs() < 1e-12);
        // Stepping a√2 along the +φ₁ direction (the (1,1)/√2 diagonal) advances
        // the first phase by exactly one turn.
        let step = c.carrier_period_px() / SQRT_2;
        let before = c.phase1_at(3.0, 4.0);
        let after = c.phase1_at(3.0 + step, 4.0 + step);
        assert!((after - before - 2.0 * PI).abs() < 1e-12);
    }

    #[test]
    fn renders_expected_dimensions_and_range() {
        let c = Checkerboard::new(6.0, 8).unwrap();
        let img = c.render(64, 48, &PatternPose::new(2.5, -1.25, 0.2));
        assert_eq!(img.width(), 64);
        assert_eq!(img.height(), 48);
        for &v in img.as_slice() {
            assert!((0.0..=1.0).contains(&v), "intensity {v} out of range");
        }
    }

    #[test]
    fn rendered_mean_sits_at_half_scale() {
        // The 50/50 claim again, but through the renderer, at an arbitrary pose.
        let c = Checkerboard::new(9.0, 8).unwrap();
        let img = c.render(512, 512, &PatternPose::new(13.7, -4.1, 0.37));
        let mean: Real =
            img.as_slice().iter().map(|&v| v as Real).sum::<Real>() / img.as_slice().len() as Real;
        assert!((mean - 0.5).abs() < 0.02, "mean intensity {mean}");
    }
}
