[package]
name = "vernier-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vernier"
path = "src/main.rs"

[features]
gpu = []

[dependencies]
argh = "0.1.19"
vernier-core = { path = "../vernier-core" }
vernier-cpu = { path = "../vernier-cpu" }
vernier-detection = { path = "../vernier-detection" }
vernier-pose = { path = "../vernier-pose" }
vernier-patterns = { path = "../vernier-patterns" }
image = { version = "0.25.10", features = ["jpeg", "png", "bmp", "tiff"] }
